services:
  api:
    build: ./server
    container_name: vtout-api
    network_mode: "host"
    env_file:
      - ./server/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: vtout-frontend
    ports:
      - "5173:80"
    restart: always

  supplier-portal:
    build: ./supplier-portal
    container_name: vtout-supplier
    ports:
      - "5174:80"
    restart: always
