services:
  api:
    build: ./server
    container_name: vtout-api
    ports:
      - "3000:3000"
    environment:
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL}
    env_file:
      - ./server/.env
    restart: always
    networks:
      - dokploy-network

  frontend:
    build: ./frontend
    container_name: vtout-frontend
    ports:
      - "5173:80"
    restart: always
    networks:
      - dokploy-network

  supplier-portal:
    build: ./supplier-portal
    container_name: vtout-supplier
    ports:
      - "5174:80"
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
